import 'package:al_ameen/data/models/data.dart';

final listofData1 = [
  Data(
      chair: '',
      id: '1',
      name: 'Muees',
      role: 'admin',
      date: DateTime(2023, 08, 02),
      time: '18:56 PM',
      amount: '100',
      description: 'haircut',
      type: 'income',
      payment: 'Paid online'),
  Data(
      chair: '',
      id: '2',
      name: 'Jaleel',
      role: 'staff',
      date: DateTime(2023, 07, 09),
      time: '15:56 PM',
      amount: '200',
      description: 'beard',
      type: 'income',
      payment: 'money'),
  Data(
      chair: '',
      id: '3',
      name: 'Anchu',
      role: 'staff',
      date: DateTime(2023, 07, 29),
      time: '11:56 PM',
      amount: '300',
      description: 'facial',
      type: 'income',
      payment: 'Paid online')
];

final listofData2 = [
  Data(
      chair: '',
      id: '1',
      name: 'Muees',
      role: 'admin',
      date: DateTime.now(),
      time: '18:56 PM',
      amount: '100',
      description: 'haircut',
      type: 'income',
      payment: 'Paid online'),
  Data(
      chair: '',
      id: '2',
      name: 'Jaleel',
      role: 'staff',
      date: DateTime.now(),
      time: '15:56 PM',
      amount: '200',
      description: 'beard',
      type: 'income',
      payment: 'money'),
  Data(
      chair: '',
      id: '3',
      name: 'Anchu',
      role: 'staff',
      date: DateTime.now(),
      time: '11:56 PM',
      amount: '300',
      description: 'facial',
      type: 'income',
      payment: 'Paid online'),
  Data(
      chair: '',
      id: '4',
      name: 'shafiq',
      role: 'staff',
      date: DateTime.now(),
      time: '11:51 PM',
      amount: '50',
      description: 'food',
      type: 'expense',
      payment: 'Paid online'),
  Data(
      chair: '',
      id: '5',
      name: 'Razak',
      role: 'staff',
      date: DateTime.now(),
      time: '11:11 PM',
      amount: '70',
      description: 'food',
      type: 'expense',
      payment: 'money')
];

final listOfData3 = [
  Data(
      chair: '',
      id: '1',
      name: 'Muees',
      role: 'admin',
      date:
          //DateTime.now(),
          DateTime(2023, 08, 02),
      time: '18:56 PM',
      amount: '100',
      description: 'lunch',
      type: 'expense',
      payment: 'Paid online'),
  Data(
      chair: '',
      id: '2',
      name: 'Jaleel',
      role: 'staff',
      date: DateTime.now(),
      //DateTime(2023, 07, 09),
      time: '15:56 PM',
      amount: '200',
      description: 'beard',
      type: 'income',
      payment: 'money'),
  Data(
      chair: '',
      id: '3',
      name: 'Anchu',
      role: 'staff',
      date: DateTime(2023, 07, 29),
      time: '11:56 PM',
      amount: '300',
      description: 'facial',
      type: 'income',
      payment: 'Paid online'),
  Data(
      chair: '',
      id: '4',
      name: 'Muees',
      role: 'admin',
      date: DateTime(2023, 08, 11),
      time: '18:56 PM',
      amount: '100',
      description: 'haircut',
      type: 'income',
      payment: 'Paid online'),
  Data(
      chair: '',
      id: '5',
      name: 'Jaleel',
      role: 'staff',
      date: DateTime(2023, 09, 09),
      time: '15:56 PM',
      amount: '200',
      description: 'beard',
      type: 'income',
      payment: 'money'),
  Data(
      chair: '',
      id: '6',
      name: 'Muees',
      role: 'staff',
      date: DateTime(2023, 09, 20),
      time: '11:56 PM',
      amount: '300',
      description: 'facial',
      type: 'income',
      payment: 'Paid online')
];

List<Data> newListOfData = [];
Data addedData = listOfData3.last;
